baseURL: "https://martinbjeldbak.com/"
title: Martin Bjeldbak Madsen
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: false

params:
  env: development # to enable google analytics, opengraph, twitter-cards and schema.
  title: Martin Bjeldbak Madsen
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Martin Bjelbak Madsen"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Martin Bjeldbak Madsen
    subtitle: "Hi, I'm Martin, a software developer. Welcome to my website!"
    imageUrl: # "https://gravatar.com/avatar/8f65973d982ab28724afc25f3530f576.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Picture of me (martin)
    buttons:
      - name: Posts
        url: posts

  # home-info mode
  homeInfoParams:
    Title: "Martin Bjeldbak Madsen"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:me@martinbjeldbak.com"
    - name: github
      url: "https://github.com/martinbjeldbak"
    - name: linkedin
      url: "https://www.linkedin.com/in/martinbjeldbak/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 20
    - identifier: blog
      name: blog
      url: /posts/
      weight: 20
    - identifier: CV
      name: vitae
      url: https://github.com/martinbjeldbak/CV/blob/master/MartinMadsenCV.pdf
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

