baseURL = "https://martinbjeldbak.com/"
languageCode = "en-us"
title = "Martin Bjeldbak Madsen"
theme = "hermit"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  [[params.social]]
    name = "github"
    url = "https://github.com/martinbjeldbak"
