[[redirects]]
  from = "https://martinbjeldbak.netlify.com"
  to = "https://martinbjeldbak.com"
  status = 200
  force = true

[[redirects]]
  from = "/cv.pdf"
  to = "https://github.com/martinbjeldbak/CV/raw/master/MartinMadsenCV.pdf"
  status = 302
