[build]
  publish = "public"
  command = "hugo --gc"

[context.production.environment]
  HUGO_VERSION = "0.68.3"

[[redirects]]
  from = "https://martinbjeldbak.netlify.com"
  to = "https://martinbjeldbak.com"
  status = 302
  force = true

[[redirects]]
  from = "/cv.pdf"
  to = "https://github.com/martinbjeldbak/CV/raw/master/MartinMadsenCV.pdf"
  status = 302
  force = true
